name: Build and Publish Release

# trigger this workflow when a new release is published

on:
  workflow_call:
    inputs:
      modid:
        required: true
        type: string
      mc-version:
        required: true
        type: string
      mod-version:
        required: true
        type: string
      curseforge-id:
        required: true
        type: number
      modrinth-id:
        required: true
        type: string
      changelog:
        required: true
        type: string
      forge:
        required: false
        type: boolean
        default: true
      fabric:
        required: false
        type: boolean
        default: true
      neoforge:
        required: false
        type: boolean
        default: true
      version-range:
        required: true
        type: string
    secrets:
      curseforge-token:
        required: true
      modrinth-token:
        required: true

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Sourcecode
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: make gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Execute Gradle build
        run: ./gradlew build

      - name: Add files to release
        uses: shogo82148/actions-upload-release-asset@v1.7.5
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: "${{ github.workspace }}/*(Fabric|Forge|Neoforge)/build/libs/${{ inputs.modid }}-*.jar"

      - name: publish NeoForge
        if: ${{ inputs.neoforge == true }}
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: ${{ inputs.modrinth-id }}
          modrinth-featured: true
          modrinth-unfeature-mode: intersection
          modrinth-token: ${{ secrets.modrinth-token }}
          modrinth-name: ${{ inputs.mc-version }} - ${{ inputs.mod-version }} - NeoForge
          modrinth-version: ${{ inputs.mc-version }}-${{ inputs.mod-version }}-NeoForge
          curseforge-id: ${{ inputs.curseforge-id }}
          curseforge-token: ${{ secrets.curseforge-token }}
          curseforge-name: ""
          curseforge-version: ""
          version-type: release
          loaders: neoforge
          files: ${{ github.workspace }}/Neoforge/build/libs/*.jar
          changelog: ${{ inputs.changelog }}
          game-versions: ${{ inputs.version-range }}
          game-version-filter: releases

      - name: publish Fabric
        if: ${{ inputs.fabric == true }}
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: ${{ inputs.modrinth-id }}
          modrinth-featured: true
          modrinth-unfeature-mode: intersection
          modrinth-token: ${{ secrets.modrinth-token }}
          modrinth-name: ${{ inputs.mc-version }} - ${{ inputs.mod-version }} - Fabric
          modrinth-version: ${{ inputs.mc-version }}-${{ inputs.mod-version }}-Fabric
          curseforge-id: ${{ inputs.curseforge-id }}
          curseforge-token: ${{ secrets.curseforge-token }}
          curseforge-name: ""
          curseforge-version: ""
          version-type: release
          loaders: fabric
          files: ${{ github.workspace }}/Fabric/build/libs/*.jar
          changelog: ${{ inputs.changelog }}
          game-versions: ${{ inputs.version-range }}
          dependencies: fabric-api(required)
          game-version-filter: releases

      - name: publish Forge
        if: ${{ inputs.forge == true }}
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: ${{ inputs.modrinth-id }}
          modrinth-featured: true
          modrinth-unfeature-mode: intersection
          modrinth-token: ${{ secrets.modrinth-token }}
          modrinth-name: ${{ inputs.mc-version }} - ${{ inputs.mod-version }} - Forge
          modrinth-version: ${{ inputs.mc-version }}-${{ inputs.mod-version }}-Forge
          curseforge-id: ${{ inputs.curseforge-id }}
          curseforge-token: ${{ secrets.curseforge-token }}
          curseforge-name: ""
          curseforge-version: ""
          version-type: release
          loaders: forge
          files: ${{ github.workspace }}/Forge/build/libs/*.jar
          changelog: ${{ inputs.changelog }}
          game-versions: ${{ inputs.version-range }}
          game-version-filter: releases
