name: Send Discord Message Mod-Release

on:
  workflow_dispatch:
    inputs:
      changelog:
        required: true
        type: string
      mc-version:
        required: true
        type: string
      mod-version:
        required: true
        type: string
      color:
        required: true
        type: number      
      ping:
        required: true
        type: string
      curseforge:
        required: true
        type: string
      modrinth:
        required: true
        type: string
      description:
        required: true
        type: string
      avatar:
        required: true
        type: string
  workflow_call:
    inputs:
      changelog:
        required: true
        type: string
      mc-version:
        required: true
        type: string
      mod-version:
        required: true
        type: string
      color:
        required: true
        type: number      
      ping:
        required: true
        type: string
      curseforge:
        required: true
        type: string
      modrinth:
        required: true
        type: string
      description:
        required: true
        type: string
      avatar:
        required: true
        type: string
    secrets:
      WEBHOOK_URL:
        required: true

jobs:
  send-discord-embed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Sourcecode
        uses: actions/checkout@v4

      - name: prepare Discord Message
        shell: bash
        run: |
          CHANGELOG="${{ inputs.changelog }}"
          CHANGELOG=${CHANGELOG//$'\n'/\\\\n}
          CHANGELOG=${CHANGELOG//\"/\\\\\"}
          CHANGELOG=${CHANGELOG//&/\\&}

          DESCRIPTION="${{ inputs.description }}"
          DESCRIPTION=${DESCRIPTION//$'\n'/\\\\n}
          DESCRIPTION=${DESCRIPTION//\"/\\\\\"}
          DESCRIPTION=${DESCRIPTION//&/\\&}

          TIMESTAMP=$(date "+%FT%T.%3NZ")

          URL="https://raw.githubusercontent.com/tristankechlo/tristankechlo/main/data/embed.json"
          wget -q -O './embed.json' "$URL"

          sed -i "s|@timestamp@|${TIMESTAMP}|g" ./embed.json
          sed -i "s|@changelog@|${CHANGELOG}|" ./embed.json
          sed -i "s|@minecraft@|"${{ inputs.mc-version }}"|g" ./embed.json
          sed -i "s|@version@|"${{ inputs.mod-version }}"|g" ./embed.json
          sed -i "s|\"@color@\"|"${{ inputs.color }}"|g" ./embed.json
          sed -i "s|@ping@|${{ inputs.ping }}|g" ./embed.json
          sed -i "s|@curseforge@|"${{ inputs.curseforge }}"|g" ./embed.json
          sed -i "s|@modrinth@|"${{ inputs.modrinth }}"|g" ./embed.json
          sed -i "s|@avatar@|"${{ inputs.avatar }}"|g" ./embed.json
          sed -i "s|@description@|${DESCRIPTION}|g" ./embed.json

          echo "# Discord Message" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "$(cat ./embed.json)" >> $GITHUB_STEP_SUMMARY

      - name: Send Discord Message
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          raw-data: ./embed.json
