name: Send Discord Message Mod-Release

on:
  workflow_call:
    inputs:
      released: # whether or not the files were released to curseforge and modrinth
        required: true
        type: boolean
      changelog: # the full changelog of the release
        required: true
        type: string
      version: # the version name of the release e.g. '1.20.4 - 1.1.1'
        required: true
        type: string
      color: # the color of the embed
        required: true
        type: number      
      content:
        required: true
        type: string
      curseforge:
        required: true
        type: string
      modrinth:
        required: true
        type: string
      github:
        required: true
        type: string
      title:
        required: true
        type: string
      description:
        required: true
        type: string
      thumbnail:
        required: true
        type: string
    secrets:
      WEBHOOK_URL:
        required: true

jobs:
  send-discord-embed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Sourcecode
        uses: actions/checkout@v4
        with:
          repository: tristankechlo/tristankechlo

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Go To Folder
        run: cd discord_embed

      - name: npm install
        run: npm ci

      - name: create .env File
        shell: bash
        run: |
          touch .env
          echo "CONTENT=\"${{ inputs.content }}\"" >> .env
          echo "CHANGELOG=\"${{ inputs.changelog }}\"" >> .env
          echo "RELEASED=\"${{ inputs.released }}\"" >> .env
          echo "TITLE=\"${{ inputs.title }}\"" >> .env
          echo "DESCRIPTION=\"${{ inputs.description }}\"" >> .env
          echo "COLOR=\"${{ inputs.color }}\"" >> .env
          echo "VERSION=\"${{ inputs.version }}\"" >> .env
          echo "CURSEFORGE=\"${{ inputs.curseforge }}\"" >> .env
          echo "MODRINTH=\"${{ inputs.modrinth }}\"" >> .env
          echo "GITHUB=\"${{ inputs.github }}\"" >> .env
          echo "THUMBNAIL=\"${{ inputs.thumbnail }}\"" >> .env

      - name: Make Embed
        run: node ./make_embed.js

      - name: Display Template
        shell: bash
        run: |
          echo "<details>" >> $GITHUB_STEP_SUMMARY
          echo "<summary><h4>.env File</h4></summary>" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo '```bash' >> $GITHUB_STEP_SUMMARY
          echo -e "$(cat ./.env)" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "</details>" >> $GITHUB_STEP_SUMMARY

          echo "" >> $GITHUB_STEP_SUMMARY

          echo "<details>" >> $GITHUB_STEP_SUMMARY
          echo "<summary><h4>Discord Message</h4></summary>" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo '```json' >> $GITHUB_STEP_SUMMARY
          echo -e "$(cat ./embed.json)" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "</details>" >> $GITHUB_STEP_SUMMARY

      - name: Send Discord Message
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          raw-data: ./embed.json
