name: Send Discord Message Mod-Release

on:
  workflow_call:
    inputs:
      changelog:
        required: true
        type: string
      version:
        required: true
        type: string
      color:
        required: true
        type: number      
      ping:
        required: true
        type: string
      curseforge:
        required: true
        type: string
      modrinth:
        required: true
        type: string
      title:
        required: true
        type: string
      description:
        required: true
        type: string
      thumbnail:
        required: true
        type: string
    secrets:
      WEBHOOK_URL:
        required: true

jobs:
  send-discord-embed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Sourcecode
        uses: actions/checkout@v4

      - name: Download Template
        shell: bash
        run: |
          URL="https://raw.githubusercontent.com/tristankechlo/tristankechlo/main/data/embed.json"
          wget -q -O './embed.json' "$URL"

      - name: Prepare Template
        shell: python
        run: |
          import datetime
          import json
          
          with open("./embed.json", "r") as f:
            data = f.read()
            f.close()
          
          changelog="""${{ inputs.changelog }}"""
          changelog = changelog.strip()
          changelog = changelog.replace("\n", "\\n")
          
          data = data.replace("@ping@", "${{ inputs.ping }}")
          data = data.replace("@title@", "${{ inputs.title }}")
          data = data.replace("@description@", "${{ inputs.description }}")
          data = data.replace("\"@color@\"", "${{ inputs.color }}")
          data = data.replace("@changelog@", changelog)
          data = data.replace("@version@", "${{ inputs.version }}")
          data = data.replace("@curseforge@", "${{ inputs.curseforge }}")
          data = data.replace("@modrinth@", "${{ inputs.modrinth }}")
          data = data.replace("@timestamp@", datetime.datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3] + "Z")
          data = data.replace("@thumbnail@", "${{ inputs.thumbnail }}")
          
          data = json.dumps(json.loads(data))
          
          with open("./embed.json", "w") as f:
            f.write(data)
            f.close()

      - name: Display Template
        shell: bash
        run: |
          echo "# Discord Message" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo '```json' >> $GITHUB_STEP_SUMMARY
          echo -e "$(python -mjson.tool ./embed.json)" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

      - name: Send Discord Message
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          raw-data: ./embed.json
